spring:
  application:
    name: message-system-add-replica
  datasource:
    source:
      hikari:
        jdbc-url: jdbc:mysql://localhost:13306/messagesystem
        username: dev_user
        password: dev_password
        driver-class-name: com.mysql.cj.jdbc.Driver
        pool-name: SourceConnectionPool
        minimum-idle: 10
        maximum-pool-size: 20
        idle-timeout: 60000
        connection-timeout: 30000
    replica:
      hikari:
        jdbc-url: jdbc:mysql://localhost:13307/messagesystem
        username: dev_user
        password: dev_password
        driver-class-name: com.mysql.cj.jdbc.Driver
        pool-name: ReplicaConnectionPool
        minimum-idle: 10
        maximum-pool-size: 20
        idle-timeout: 60000
        connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  data:
    redis:
      host: localhost
      port: 16379
      repositories:
        enabled: false

logging:
  level:
    org.springframework.security.web.context: TRACE
    org.springframework.security.core.context: TRACE


